apiVersion: v1
kind: Pod
metadata:
  name: builder
  namespace: devops
  labels:
    name: builder
spec:
  serviceAccount: jenkins
  containers:
  - name: builder
    image: jenkins/jnlp-agent-docker:latest
    command:
    - cat
    tty: true
