apiVersion: v1
kind: Pod
metadata:
  name: builder
  labels:
    name: builder
spec:
  containers:
  - name: builder
    image: jenkins/jnlp-agent-docker:latest
    command:
    - docker
    tty: true
