apiVersion: v1
kind: Pod
metadata:
  name: builder
  labels:
    name: builder
spec:
  containers:
  - name: builder
    image: jenkins/jnlp-agent-docker:latest
    command:
    - sh 'docker build -t amihaiba/eltamvc:0.1.0 ./eltaMVC/'
