# Jenkins master deployment
jenkins: 
  name: jenkins
  namespace: devops
  replicas: 1
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
  container: 
    image: jenkins/jenkins:2.401.1-lts
  service:
    kind: NodePort
    ports:
      http: 8080
      jnlp: 50000
      nodePort: 32000
  volumes:
    name: jenkins-data
    mountPath: /var/jenkins_home
    storageClassName: local-storage
  pvc:
    name: jenkins-pvc