apiVersion: v1
kind: Pod
metadata:
  name: deployer
  namespace: devops
  labels:
    app: deployer
spec:
  serviceAccount: jenkins
  containers:
  - name: deployer
    image: dtzar/helm-kubectl:3.12
    command:
    - cat
    resources:
      limits:
        cpu: "500m"
        memory: "1024Mi"
    tty: true
