apiVersion: v1
kind: Pod
metadata:
  name: deployer
  namespace: devops
  labels:
    app: deployer
spec:
  serviceAccount: jenkins
  containers:
  - name: deployer
    image: bitnami/kubectl:1.27.2
    command:
    - cat
    resources:
      limits:
        cpu: "500m"
        memory: "1024Mi"
    tty: true
  #   volumeMounts:
  #   - name: docker-socket
  #     mountPath: /var/run/docker.sock
  # volumes:
  # - name: docker-socket
  #   hostPath:
  #     path: /var/run/docker.sock
