apiVersion: apps/v1
kind: Deployment
metadata:
  name: eltamvc
spec:
  selector:
    matchLabels:
      app: eltamvc
  template:
    metadata:
      labels:
        app: eltamvc
    spec:
      containers:
      - name: eltamvc
        image: amihaiba/eltamvc:0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
