# Sample app deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eltamvc
  namespace: prod
spec:
  selector:
    matchLabels:
      app: eltamvc
  template:
    metadata:
      labels:
        app: eltamvc
    spec:
      containers:
      - name: eltamvc
        image: amihaiba/eltamvc:0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---

# Sample app service
apiVersion: v1
kind: Service
metadata:
  name: eltamvc
  namespace: prod
spec:
  type: NodePort
  selector:
    app: eltamvc
  ports:
  - port: 5000
    targetPort: 5000
