# Jeknins master deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccount: jenkins
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.401.1-lts
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: jenkins-data
            mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins
  type: NodePort  
  ports:
    - name: http-port
      port: 8080
      targetPort: 8080
      nodePort: 32000
    - name: jnlp-port
      port: 50000
      targetPort: 50000

# # Jenkins NodePort service to expose UI
# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins
#   namespace: devops
# spec:
#   type: NodePort
#   ports:
#     - port: 8080
#       targetPort: 8080
#       nodePort: 30000
#   selector:
#     app: jenkins
# ---

# # Jenkins internal service to communicate with agents
# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins-jnlp
#   namespace: devops
# spec:
#   type: ClusterIP
#   ports:
#     - port: 50000
#       targetPort: 50000
#   selector:
#     app: jenkins
